-- Users table seeds here (Example)
INSERT INTO users (email, trip_id)
VALUES
  ('john.doe@gmail.com', 1),        -- John Doe with Gmail for 'Summer Vacation'
  ('jane.smith@yahoo.com', 2),      -- Jane Smith with Yahoo for 'Business Conference'
  ('robert.johnson@outlook.com', 3),-- Robert Johnson with Outlook for 'Family Reunion'
  ('susan.jackson@gmail.com', 4),   -- Susan Jackson with Gmail for 'Adventure Expedition'
  ('michael.wilson@yahoo.com', 1),  -- Michael Wilson with Yahoo for 'Summer Vacation'
  ('emily.martin@outlook.com', 2),  -- Emily Martin with Outlook for 'Business Conference'
  ('david.anderson@gmail.com', 3),  -- David Anderson with Gmail for 'Family Reunion'
  ('lisa.brown@yahoo.com', 4),      -- Lisa Brown with Yahoo for 'Adventure Expedition'
  ('william.thomas@gmail.com', 1),  -- William Thomas with Gmail for 'Summer Vacation'
  ('sarah.moore@yahoo.com', 2),     -- Sarah Moore with Yahoo for 'Business Conference'
  ('richard.davis@outlook.com', 3), -- Richard Davis with Outlook for 'Family Reunion'
  ('linda.white@gmail.com', 4),     -- Linda White with Gmail for 'Adventure Expedition'
  ('james.jones@yahoo.com', 1),     -- James Jones with Yahoo for 'Summer Vacation'
  ('mary.miller@gmail.com', 2),     -- Mary Miller with Gmail for 'Business Conference'
  ('joseph.johnson@outlook.com', 3),-- Joseph Johnson with Outlook for 'Family Reunion'
  ('patricia.moore@yahoo.com', 4),  -- Patricia Moore with Yahoo for 'Adventure Expedition'
  ('john.wilson@gmail.com', 1),     -- John Wilson with Gmail for 'Summer Vacation'
  ('elizabeth.martin@yahoo.com', 2), -- Elizabeth Martin with Yahoo for 'Business Conference'
  ('michael.anderson@outlook.com', 3),-- Michael Anderson with Outlook for 'Family Reunion'
  ('susan.jackson@gmail.com', 4),   -- Susan Jackson with Gmail for 'Adventure Expedition'
  ('david.wilson@yahoo.com', 1),    -- David Wilson with Yahoo for 'Summer Vacation'
  ('emily.martin@outlook.com', 2),  -- Emily Martin with Outlook for 'Business Conference'
  ('robert.brown@gmail.com', 3),    -- Robert Brown with Gmail for 'Family Reunion'
  ('lisa.davis@yahoo.com', 4),      -- Lisa Davis with Yahoo for 'Adventure Expedition'
  ('michael.smith@gmail.com', 1),   -- Michael Smith with Gmail for 'Summer Vacation'
  ('sarah.miller@yahoo.com', 2),    -- Sarah Miller with Yahoo for 'Business Conference'
  ('richard.johnson@outlook.com', 3),-- Richard Johnson with Outlook for 'Family Reunion'
  ('linda.wilson@gmail.com', 4);    -- Linda Wilson with Gmail for 'Adventure Expedition'