-- Seed data for the itinerary_items table
-- INSERT INTO itinerary_items (
--   itinerary_id, 
--   trip_id, 
--   lat, 
--   lng, 
--   address, 
--   phone, 
--   name, 
--   rating,  -- Modify the rating value as needed (e.g., 4.5)
--   user_ratings_total, 
--   url, 
--   opening_hours, 
--   website, 
--   type, 
--   photos, 
--   icon, 
--   completed
-- ) 
-- VALUES (
--   1,
--   1,
--   34.052200,
--   -118.243700,
--   '123 Main St, Los Angeles, CA',
--   '123-456-7890',
--   'Example Place',
--   4.5,
--   100,
--   'https://example.com',
--   '["Monday: 10:00 AM – 9:00 PM", "Tuesday: 10:00 AM  - 9:00 PM"]',
--   'https://example.com',
--   'Restaurant',
--   '["photo1.jpg", "photo2.jpg"]',
--   'restaurant_icon.png',
--   FALSE
-- );