DROP TABLE IF EXISTS trips CASCADE;

-- check syntax unique
CREATE TABLE trips  (
  id SERIAL PRIMARY KEY NOT NULL,
  trip_url VARCHAR(255) UNIQUE NOT NULL,
  trip_name VARCHAR(255) NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  trip_location VARCHAR(255) NOT NULL,
  is_editable BOOLEAN NOT NULL DEFAULT TRUE
);